server:
  port: 8080

logging:
  level:
    com.martinachov.hexagonal: info

spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver: org.h2.Driver
    username: www-data
    password: www-data
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update  
